---
- name: precondition for weave network
  command: sysctl net.bridge.bridge-nf-call-iptables=1
  register: out

- debug: var=out.stdout_lines

- name: set up weave network
  become: yes
  become_user: ubuntu
  shell: export kubever=$(kubectl version | base64 | tr -d '\n') && kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
  ignore_errors: True
...
