---
- name: get api address
  shell: ifconfig eth0 | grep 'inet'| cut -d':' -f2 | awk '{print $2}'
  register: ip_addr

- debug: var=ip_addr.stdout_lines

- name: Initialize the Kubernetes cluster using kubeadm
  shell: kubeadm init --pod-network-cidr=10.4.0.0/16 --service-cidr=10.5.0.0/16 --service-dns-domain=k8s.local --apiserver-advertise-address={{ ip_addr.stdout }}
  ignore_errors: True

- name: create .kube directory
  become: yes
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
...
