---
- name: disable SWAP since Kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a

- name: disable SWAP in fstab since Kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: enable netfilter
  command: modprobe br_netfilter

- name: install Docker
  apt:
      name: docker.io
      state: present
      update_cache: true

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true

- name: reload the daemon
  command: systemctl daemon-reload

- name: restart dockerd
  service:
    name: docker
    state: restarted

- name: install APT Transport HTTPS
  apt:
      name: apt-transport-https
      state: present

- name: add Kubernetes apt-key
  apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

- name: add Kubernetes APT repository
  apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: "kubernetes"

- name: install kubelet, kubeadm, and kubectl
  apt:
    force_apt_get: yes
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: configure Kubernetes cgroup driver to match Dockers (cgroupfs)
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertbefore: '^ExecStart'
    firstmatch: yes
    line: 'Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"'
    state: present

- name: reload daemon
  command: systemctl daemon-reload

- name: restart kubelet
  command: systemctl restart kubelet

- name: restart dockerd
  service:
    name: docker
    state: restarted

- name: pull kube images
  become: true
  shell: kubeadm config images pull
