---
- name: reset Kubernetes workers (just in case)
  command: kubeadm reset -f
  register: out
  ignore_errors: true

- name: join workers
  vars:
    join_command: "{{ lookup('file', './current_cluster/kubeadm-init.txt') }}"
  # shell: "{{ join_command.stdout_lines[-1] }} --ignore-preflight-errors=all"
  shell: "{{ join_command }} --ignore-preflight-errors=all --v=5"
  register: out
  ignore_errors: false
  become: true

- debug: var=out.stdout_lines
...